import request from './request'

export const login = (data) => request.post('/auth/login', data)
export const listServers = () => request.get('/servers')
export const listProjects = (params) => request.get('/projects', { params })
export const getProject = (id) => request.get(`/projects/${id}`)
export const createProject = (data) => request.post('/projects', data)
export const updateProject = (id, data) => request.put(`/projects/${id}`, data)
export const deleteProject = (id) => request.delete(`/projects/${id}`)
export const getHostMetrics = (params) => request.get('/metrics/host', { params })
export const getLatestHostMetrics = (serverId) => request.get('/metrics/host/latest', { params: { serverId } })
export const getProcessMetrics = (params) => request.get('/metrics/process', { params })
export const getLatestProcessMetrics = (projectId) => request.get('/metrics/process/latest', { params: { projectId } })
export const getHealthChecks = (params) => request.get('/health-checks', { params })
export const triggerHealthCheck = (projectId) => request.post(`/health-checks/trigger/${projectId}`)
export const listErrors = (params) => request.get('/errors', { params })
export const getErrorDetail = (id) => request.get(`/errors/${id}`)
export const resolveError = (id) => request.patch(`/errors/${id}`)
export const listAlertRules = () => request.get('/alert-rules')
export const createAlertRule = (data) => request.post('/alert-rules', data)
export const updateAlertRule = (id, data) => request.put(`/alert-rules/${id}`, data)
export const deleteAlertRule = (id) => request.delete(`/alert-rules/${id}`)
export const listAlertLogs = (params) => request.get('/alert-logs', { params })
export const listDeployments = (params) => request.get('/deployments', { params })
export const createDeployment = (data) => request.post('/deployments', data)
export const updateDeployment = (id, data) => request.put(`/deployments/${id}`, data)
export const deleteDeployment = (id) => request.delete(`/deployments/${id}`)
